from tkinter import *
main = Tk()
main.title("WEEKEND ICON BAR")
def Click():
 mybutton1 = Button(main,text = "Sunday",padx = 2, pady = 3)
 mybutton1.grid()
 mybutton2 = Button(main, text = "Monday", padx= 4,pady = 5)
 mybutton2.grid()
 mybutton3 = Button(main,text = "Tuesday", padx = 6, pady= 7)
 mybutton3.grid()
 mybutton4 = Button(main, text = "Wednesday", padx = 8, pady = 9)
 mybutton4.grid()
 mybutton5 = Button(main, text = "Thrusday", padx = 8, pady = 9)
 mybutton5.grid()
 mybutton6 = Button(main, text = "Friday", padx = 8, pady = 9)
 mybutton6.grid()
 mybutton7 = Button(main, text = "Saturday", padx = 8, pady = 9)
 mybutton7.grid()
my_function_call = Button(main, text ="Click me !", command= Click, padx = 10, pady =12)
my_function_call.grid()
main.mainloop()